name: Puppeteer Screenshot file
description: '지정된 경로에 있는 파일을 스크린샷을 찍어 보내주는 액션입니다.'
inputs:
  target-file-path:
    description: 'target file - Ex) /mochawesome-report/mochawesome.html'
    required: true
  slack-token:
    description: 'slack auth token'
    required: true
  slack-channels:
    description: 'target slack channel id'
    required: true
  img-name:
    description: 'response img file name - default: test'
    required: false
  img-type:
    description: 'response img file type - default: jpeg'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'blue'
